import type { Project } from './supabase';

/** Static seed data when Supabase is unavailable. No external image URLs. */
export const FALLBACK_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Neuro Flow',
    slug: 'neuro-flow',
    description: 'Autonomous multi-agent system for visual web automation with real-time task tracking.',
    technical_challenge: 'Browser agents stalled on dynamic SPAs with opaque DOM trees and no retry semantics.',
    architecture: 'Next.js orchestrator · Puppeteer workers · pgvector memory · Redis job queue',
    impact_metrics: [
      { label: 'Task success', value: '94%' },
      { label: 'Avg. latency', value: '1.2s' },
      { label: 'Workflows/day', value: '2.4k' },
    ],
    category: 'AI',
    thumbnail: null,
    tech_stack: ['Next.js', 'TypeScript', 'Puppeteer', 'pgvector', 'Redis'],
    github_url: 'https://github.com/krishbaresha/neuro-flow',
    live_url: 'https://neuro-flow.vercel.app',
    featured: true,
    sort_order: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Aurora Canvas',
    slug: 'aurora-canvas',
    description: 'WebGL metrics dashboard with reactive flow fields and sub-16ms frame budgets.',
    technical_challenge: 'Rendering 120k particles on integrated GPUs without thermal throttling or jank.',
    architecture: 'R3F scene graph · GLSL compute passes · GSAP scrub timeline · OffscreenCanvas workers',
    impact_metrics: [
      { label: 'Frame time', value: '12ms' },
      { label: 'GPU memory', value: '-38%' },
      { label: 'Engagement', value: '+61%' },
    ],
    category: 'WebGL',
    thumbnail: null,
    tech_stack: ['Three.js', 'WebGL', 'GSAP', 'React Three Fiber', 'GLSL'],
    github_url: 'https://github.com/krishbaresha/aurora-canvas',
    live_url: 'https://aurora-canvas.vercel.app',
    featured: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Synapse RAG',
    slug: 'synapse-rag',
    description: 'Local-first RAG engine for real-time document intelligence and semantic search.',
    technical_challenge: 'Sub-200ms retrieval across 500k chunks on a single Postgres instance.',
    architecture: 'pgvector HNSW · Hybrid BM25 rerank · Gemini embeddings · FastAPI ingest pipeline',
    impact_metrics: [
      { label: 'P95 query', value: '180ms' },
      { label: 'Recall@10', value: '0.91' },
      { label: 'Cost/query', value: '-72%' },
    ],
    category: 'AI',
    thumbnail: null,
    tech_stack: ['Python', 'pgvector', 'PostgreSQL', 'Gemini API', 'FastAPI'],
    github_url: 'https://github.com/krishbaresha/synapse-rag',
    live_url: 'https://synapse-rag.vercel.app',
    featured: false,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Dashboard Forge',
    slug: 'dashboard-forge',
    description: 'SaaS analytics hub with live charts, cohort segmentation, and webhook pipelines.',
    technical_challenge: 'Streaming 50k events/min into dashboards without overloading the client bundle.',
    architecture: 'Next.js RSC · Supabase Realtime · Edge cron · Recharts lazy islands',
    impact_metrics: [
      { label: 'TTI', value: '0.9s' },
      { label: 'Bundle', value: '-44%' },
      { label: 'MRR tracked', value: '$1.2M' },
    ],
    category: 'SaaS',
    thumbnail: null,
    tech_stack: ['Next.js', 'Supabase', 'Recharts', 'TypeScript', 'Tailwind'],
    github_url: 'https://github.com/krishbaresha/dashboard-forge',
    live_url: null,
    featured: false,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Prompt Forge',
    slug: 'prompt-forge',
    description: 'Prompt engineering studio with chain-of-thought debugging and model comparison.',
    technical_challenge: 'Diffing multi-turn prompt versions across providers with deterministic replay.',
    architecture: 'React SPA · LangChain adapters · SQLite version store · SSE streaming UI',
    impact_metrics: [
      { label: 'Eval cycles', value: '3× faster' },
      { label: 'Token waste', value: '-35%' },
      { label: 'Teams', value: '12' },
    ],
    category: 'AI',
    thumbnail: null,
    tech_stack: ['React', 'OpenAI', 'Anthropic', 'LangChain', 'Node.js'],
    github_url: 'https://github.com/krishbaresha/prompt-forge',
    live_url: null,
    featured: false,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Motion Studio',
    slug: 'motion-studio',
    description: 'Visual animation composer with live Framer Motion preview and code export.',
    technical_challenge: 'Bidirectional sync between a visual timeline editor and generated motion code.',
    architecture: 'Monaco editor · AST transform layer · Framer Motion runtime · Vite HMR shell',
    impact_metrics: [
      { label: 'Ship time', value: '-50%' },
      { label: 'Handoff bugs', value: '-80%' },
      { label: 'Exports/wk', value: '340' },
    ],
    category: 'Full Stack',
    thumbnail: null,
    tech_stack: ['React', 'Framer Motion', 'Monaco Editor', 'TypeScript'],
    github_url: 'https://github.com/krishbaresha/motion-studio',
    live_url: null,
    featured: false,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
